services:
  - type: web
    name: check-insurance-backend
    env: python
    plan: starter
    region: frankfurt

    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000

    autoDeploy: true

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

      - key: DATABASE_URL
        sync: false

      - key: AUTH_SECRET
        sync: false

      - key: ADMIN_EMAIL
        value: admin@checkrisk.com

      - key: ADMIN_PASSWORD
        sync: false

      - key: API_PREFIX
        value: /api
